### ISSUE TITLE
UPX v4.2.0 Task List

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#686]
Experiment: using a GitHub issue+tasklists; this will be updated frequently; feel free to add comments; comments that are done will be hidden/collapsed; no actual discussions here, use existing or new issues instead!

### UPX v4.2.0 Milestone
https://github.com/upx/upx/milestone/13

### macOS
- [x] disable packing macOS binaries

### Unsorted
- [x]  update file `NEWS`
- [x] CI: create weekly-ci runtime checker runs: ASAN, MSAN, Valgrind, QEMU

**Comment by markus-oberhumer** [comment]
@jreiser 4.1.0 is released, and i have FORCE pushed a new devel4 branch

```
# make sure that git is clean and that all your local changes are committed in some local branch!

git fetch --all --prune
git checkout devel4
git reset --hard origin/devel4      # DANGER is here
git submodule update --init

# DONE, now you can `git rebase -i` your local branches onto devel4

```

**Comment by markus-oberhumer** [comment]
@jreiser Please double-check commit https://github.com/upx/upx/commit/b9bf81d548e82fb332edb45954bca3a7eab11779

**Comment by jreiser** [comment]
@markus-oberhumer Of course it is "OK" (initializing a member that contains no pointers is always OK), but I do not see what the problem was.

**Comment by markus-oberhumer** [comment]
The problem is that this might indicate a bug (try a UPX version **before** the fix):

```sh
$ rm -rf ./build/xtarget/clang-msan

$ flags="-fsanitize=memory -fsanitize=undefined -fno-omit-frame-pointer -D__SANITIZE_ADDRESS__=1 -DDOCTEST_CONFIG_DISABLE=1"
$ make UPX_XTARGET=clang-msan xtarget/release CC="clang $flags" CXX="clang++ $flags" UPX_CMAKE_CONFIG_FLAGS=-DUPX_CONFIG_DISABLE_WERROR=ON

$ env -C ./build/xtarget/clang-msan/release $PWD/misc/testsuite/upx_testsuite_1.sh
```

Result:

```
=============================================================================
t160_compress_all_methods_1_no_filter
=============================================================================

# t020_canonicalized/amd64-linux.elf/upx-3.91
==59015==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5ebbba in PackLinuxElf::defineSymbols(Filter const*) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x5ebbba) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #1 0x5fb938 in PackLinuxElf64::buildLinuxLoader(unsigned char const*, unsigned int, unsigned char const*, unsigned int, Filter const*) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x5fb938) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #2 0x831b2c in Packer::compressWithFilters(unsigned char*, unsigned int, unsigned char*, unsigned char*, unsigned int, unsigned char*, unsigned int, Filter*, unsigned int, upx_compress_config_t const*, int, bool) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x831b2c) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #3 0x833a18 in Packer::compressWithFilters(Filter*, unsigned int, upx_compress_config_t const*, int, unsigned int, unsigned int, unsigned int, unsigned char*, unsigned int, bool) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x833a18) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #4 0x83361f in Packer::compressWithFilters(Filter*, unsigned int, upx_compress_config_t const*, int, bool) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x83361f) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #5 0x629737 in PackLinuxElf64::pack1(OutputFile*, Filter&) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x629737) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #6 0x63b4be in PackLinuxElf64amd::pack1(OutputFile*, Filter&) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x63b4be) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #7 0x7861e6 in PackUnix::pack(OutputFile*) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x7861e6) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #8 0x81e337 in Packer::doPack(OutputFile*) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x81e337) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #9 0x8e6cc3 in do_one_file(char const*, char*) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x8e6cc3) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #10 0x8e8494 in do_files(int, int, char**) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x8e8494) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #11 0x5a1b6a in upx_main(int, char**) (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x5a1b6a) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #12 0x5a2c31 in main (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x5a2c31) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)
    #13 0x7fbb13732b49 in __libc_start_call_main (/lib64/libc.so.6+0x27b49) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #14 0x7fbb13732c0a in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x27c0a) (BuildId: 245240a31888ad5c11bbc55b18e02d87388f59a9)
    #15 0x456964 in _start (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x456964) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472)

SUMMARY: MemorySanitizer: use-of-uninitialized-value (/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx+0x5ebbba) (BuildId: 83c2e61da17bf8eb0f6ef3cccfd60ffb375ee472) in PackLinuxElf::defineSymbols(Filter const*)
Exiting
FATAL: '/mnt/local/home-extra-storage-fast/home/mfx/code/github/upx/upx4/build/xtarget/clang-msan/release/upx' -qq --prefer-ucl --all-methods -1 --no-filter t020_canonicalized/amd64-linux.elf/upx-3.91 -o t160_compress_all_methods_1_no_filter/amd64-linux.elf/upx-3.91
  (exit code was 1)



```













```

**Comment by jreiser** [comment]
@markus-oberhumer Thank you for supplying the context `rm -rf ./build/xtarget/clang-msan; <<snip>>`.  Otherwise the string "MSAN" (case-independent) does not appear until *after* a build+run of the testsuite with your parameters.  (I have encountered analogous problems a few times before.  I welcome your input, but please include enough to reproduce the problem!)

The complaint `MemorySanitizer: use-of-uninitialized-value;     #0 0x5ebbba in PackLinuxElf::defineSymbols` is a don't-care which arises during the initial computation of the storage cost for the stub given a set of specific parameters.  The code is
```
void PackLinuxElf::defineSymbols(Filter const *)
{
    linker->defineSymbol("O_BINFO", (!!opt->o_unix.is_ptinterp) | o_binfo);
}
```
which triggers a complaint from MSAN when `o_binfo` is undefined.  However valgrind does NOT complain, because valgrind tracks bitwise, and the second parameter has the LSB usually defined by the `!!.is_ptinterp`, with 31 higher-order bits of Undefined by `o_binfo`.  As long as the Undefined bits are only copied, and never used to make decisions or for Output, then valgrind does not complain.  [I wish that valgrind had an optional mode for "Complain as soon as any Undefined bit is fetched."  However gcc has been prone to "over-fetch" (fetch 32 bits when only 16 were requested; or fetch the entire enclosing bytes when the source asks for just a narrow-er bit field).  Valgrind got tired of explaining the "don't care" complaints for such situations, so Valgrind adopted bit-by-bit checking.  However sometimes I really do want "eager" complaints.]

The larger context is
```
void PackLinuxElf64amd::pack1(OutputFile *fo, Filter &ft)
{
    super::pack1(fo, ft);   // *** MSAN complains of Undefined o_binfo when
        // *** buildLinuxLoader() is called multiple times from here
        // *** when exploring the size of the  stub for each candidate {method, filter, etc.}
    if (0!=xct_off)  // shared library
        return;
    generateElfHdr(fo, stub_amd64_linux_elf_fold, getbrk(phdri, e_phnum) );
       // *** o_binfo is defined here before buildLinuxLoader() is called for final output
}   
```
Because the bits of `o_binfo` have no impact on the `sizeof` the stub, then Undefined `o_binfo` does not matter until the final output.

**Comment by markus-oberhumer** [comment]
Thanks for the detailed info, makes sense!

JFYI, I'm working on adding weekly-CI ASAN+MSAN+valgrind builds and checks.

**Comment by markus-oberhumer** [comment]
@jreiser I have FORCE pushed devel4 once again to keep the git history clean. See instructions above.

**Comment by markus-oberhumer** [comment]
@jreiser please have a look at commit  https://github.com/upx/upx/commit/cfa8107ab99f932752d7e1b15d28b61beba01185 and my comments in p_mach.cpp

**Comment by markus-oberhumer** [comment]
@jreiser I have FORCE pushed devel4 once again to keep the git history clean. See instructions above.

**Comment by markus-oberhumer** [comment]
@jreiser submodules have been updated

**Comment by markus-oberhumer** [comment]
@jreiser submodules have been updated once again

**Comment by markus-oberhumer** [comment]
@jreiser now that macOS 14 has been released, should I move the macOS issues to milestone 4.3.0 ?

**Comment by markus-oberhumer** [comment]
@jreiser I have FORCE pushed devel4 to cleanup some commits

**Comment by markus-oberhumer** [comment]
@jreiser yet another devel4 FORCE push
