### ISSUE TITLE
UPX v9.9.9 Task List

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#720]
[**NOTE**: this issue is just a  **dummy text placeholder**]

Experiment: using a GitHub issue+tasklists; this will be updated frequently; feel free to add comments; comments that are done will be hidden/collapsed; no actual discussions here, use existing or new issues instead!

### UPX v9.9.9 Milestone
https://github.com/upx/upx/milestone/999

### Android
- [x] https://github.com/upx/upx/issues/700
- [x] https://github.com/upx/upx/issues/710

### macOS
- [ ] add support for macOS 13+ and enable packing again
- [x] https://github.com/upx/upx/issues/434
- [x] https://github.com/upx/upx/issues/446
- [x] https://github.com/upx/upx/issues/601
- [ ] https://github.com/upx/upx/issues/612
- [ ] https://github.com/upx/upx/issues/555 (this is probably ready, try the zigcc macos GitHub Actions CI artifacts)

### Windows
- [ ] https://github.com/upx/upx/issues/154 **NEED HELP**
- [ ] https://github.com/upx/upx/issues/559 **NEED HELP**
- [ ] https://github.com/upx/upx/issues/670 **NEED HELP**
- [ ] **TODO INVESTIGATE**: GitHub Actions CI artifact `zigcc i386-windows-gnu` upx.exe, when self-packed, produces an interesting error: ```libc++abi: terminating due to uncaught exception of type CantPackException: std::exception```; that does not  happen for the unpacked upx.exe, and it might be flaky; zig or UPX problem? @markus-oberhumer
  -  UPDATE: the i686 llvm-mingw builds suffer the same problem https://github.com/upx/upx/actions/workflows/weekly-ci-cc-llvm-mingw.yml ; so clang/lld/libunwind or UPX problem?
  - low priority
- [ ] **TODO INVESTIGATE**: check Alpine Linux 3.11 and Alpine Linux 3.12 binaries from https://github.com/upx/upx/actions/workflows/weekly-ci-cc-alpine-mingw.yml ; mingw-w64-gcc or wine problem?
  - Alpine Linux >= 3.13 works, so extremely low priority

**Comment by necros2k7** [comment]
https://github.com/upx/upx/milestone/999 - link is 404

**Comment by markus-oberhumer** [comment]
**NOTE**: this v9.9.9 thing is just a **dummy text placeholder** so that I can easily copy relevant parts/notes to other (real) issues.

There is no (planned) version 9.9.9 :smile: 

So please just ignore this issue.

**Comment by markus-oberhumer** [comment]
Setting this issue to closed as it seems I can still do personal edits.
