### ISSUE TITLE
UPX v5.0.0 Task List

### ISSUE THREAD

**Issue by markus-oberhumer** [upx/upx#735]
Experiment: using a GitHub issue+tasklists; this will be updated frequently; feel free to add comments; comments that are done will be hidden/collapsed; no actual discussions here, use existing or new issues instead!

### UPX v5.0.0 Milestone
https://github.com/upx/upx/milestone/18

### Android
- [x] https://github.com/upx/upx/issues/700
- [x] https://github.com/upx/upx/issues/710

### Linux
- [x] merge jreiser branch (might also fix Android issues)
- [x] extensive testing of merged jreiser branch
- [x] test all files from https://github.com/upx/upx-testsuite-v2 for **regressions** !!!

### macOS
- [ ] need some official plan/statement how to continue; broken and stalled since macOS 13 (2022); blame Apple
- [ ] relevant issue: https://github.com/upx/upx/issues/612

### Unsorted
- [ ] consider disabling/removing all bvmlinuz/vmlinux/vmlinuz sources; possible bit rot
- [ ] check the status of the BSD variants; disable/remove them if bit rot
  - looks like nobody is using BSD any longer; would need at least a free CI account for testing
- [ ] check if i386 ELF "execve" and "shell" variants still do work
  - they probably are fine but could use some testsuite coverage

**Comment by markus-oberhumer** [comment]
@jreiser Could you please revisit doc/elf-to-mem.txt and doc/selinux.txt, at least to make sure they contain no obvious errors/outdated infos? Thanks.

**Comment by jreiser** [comment]
doc/selinux.txt needed no changes.  I revised doc/elf-to-mem.txt in 55b69124374feacab7bb0d0467f462a992d453b2 on branch `devel4`.

**Comment by markus-oberhumer** [comment]
@jreiser I have FORCE pushed a new devel4 branch, including submodule updates:

```
# make sure that git is clean and that all your local changes are committed in some local branch!

git fetch --all --prune
git checkout devel4
git reset --hard origin/devel4      # DANGER is here
git submodule update --init

# DONE, now you can `git rebase -i` your local branches onto devel4

```

**Comment by jreiser** [comment]
@markus-oberhumer I am not going to use `rebase` because it tends to double or triple the work for me.  I have more than a dozen commits on a private branch, and there are a handful of commits on `devel4` after the split.  `rebase` will require [the equivalent of] at least 20 commits, often including large portions of the same subsets of individual commits several times in a row.  Yes, I know of `rerere`, but that is much to learn, fragile, and in previous attempts has failed often.

Instead, I will create a new private branch based on today's `devel4`, then `merge` my private branch into it, and then use the result for further development, eventually discarding the existing private branch.

I have considered the points made in https://stackoverflow.com/questions/20348629/what-are-the-advantages-of-keeping-linear-history-in-git , and agree with many of them, both for and against requiring linear history.  To me, the overriding reason is that `rebase` causes **lies** in the linear history that it produces.  Development and actual history happens in parallel, and forcing linear history invents history that did not happen.  (In some cases actual portions of history can be erased.) The nicest benefit of linear history is simpler `revert` and `cherry-pick`, but forcing linear history forces doing all the work ahead of time, when 90% or more of commits never need it.

**Comment by markus-oberhumer** [comment]
Git is **not** about "history", it's about managing distributed software development that can easily get reviewed with `gitk`, `git blame` and `git bisect`.  Immutability is achieved with `git tag`.  We do not care about "true" history between tags.

`git rebase -i` (**NOTE** the `-i` flag!) is extremely easy to use and often much simpler/more powerful than `git merge`.

`git rebase -i` also allows you to reorder and squash commits, which is a huge QOL feature WRT to the actual commits.

Many large Open Source projects use a (mostly) linear Git history (Kernel, LLVM, gcc, Go, QEMU, Wine, ...) because otherwise this is just a huge mess. 

And if you really care about **fully immutable history** you can use a SCM like Fossil https://www.fossil-scm.org/home/doc/trunk/www/index.wiki . But then you typically need patch queues etc - which is basically the same thing as a hidden `git rebase` anyway.

**Comment by markus-oberhumer** [comment]
@jreiser I've added some bounds checking code to MemBuffer and now the testsuite fails. Please have a look!

**Comment by jreiser** [comment]
> I've added some bounds checking code to MemBuffer and now the testsuite fails. Please have a look!

Please display some cases which fail.  It works for me:
```
$ git checkout d849e9de98266e8ce35ad10dd88bd254bbed3db3
HEAD is now at d849e9de src: add some bounds checking to MemBufferBase
$ git submodule update

$ cd src
$ make run-testsuite >testsuite.out 2>&1
$ echo $?
0  # success

$ head testsuite.out
make -C ./.. build/release
make[1]: Entering directory '$PATH/upx'
cmake --build build/release --parallel --config Release
gmake[2]: Entering directory '$PATH/upx/build/release'
[ 14%] Built target upx_vendor_zlib
[ 34%] Built target upx_vendor_ucl
[100%] Built target upx
gmake[2]: Leaving directory '$PATH/upx/build/release'
make[1]: Leaving directory '$PATH/upx'
time -p bash ./../misc/testsuite/upx_testsuite_1.sh

$ tail testsuite.out
upx_testsuite_BUILDDIR='$PATH/src/tmp-upx-testsuite-release'
.sha256sums.{expected,current} counts:
    189     378   17559
    189     378   17559

UPX testsuite passed. All done.
real 37.48
user 35.83
sys 1.65
make[1]: Leaving directory '$PATH/src'
```

**Comment by markus-oberhumer** [comment]
Hmm, it looks like "make test" is failing https://github.com/upx/upx/actions/runs/7728768012/job/21070385170

The actual ubuntu binaries are uploaded before running the test and available at https://github.com/upx/upx/actions/runs/7728768012

**Comment by jreiser** [comment]
`MemBufferBase<unsigned char>::operator[]` objects to `&membuf[N]` where `N` is the declared length.  The standard explicitly allows taking the address of "just beyond the high-address end", so the test is too strict.

**Comment by markus-oberhumer** [comment]
I see, thanks!

**Comment by markus-oberhumer** [comment]
More than 30 years of expertise with C++, and still struggling... :smile:

**Comment by markus-oberhumer** [comment]
@jreiser My current `test-misc` branch on GitHub Actions reveals that UPX compressed programs won't work under valgrind. I'm unsure if this is an UPX or valgrind problem and if we should tackle this. What do you think?

**Comment by jreiser** [comment]
> UPX compressed programs won't work under valgrind.

In order to evaluate what to do, I need the URL of an explicit executable that fails to work.

**Comment by markus-oberhumer** [comment]
Ubuntu 22.04 binaries are at https://github.com/upx/upx/actions/runs/7742845948 . Compress upx with itself and run the packed upx under valgrind (or see misc/testsuite/mimic_ctest.sh).

**Comment by jreiser** [comment]
```
==55912== Memcheck, a memory error detector
==55912== Copyright (C) 2002-2022, and GNU GPL'd, by Julian Seward et al.
==55912== Using Valgrind-3.22.0 and LibVEX; rerun with -h for copyright info
==55912== Command: ./upx.packed --version-short
==55912== 
==55912== Invalid read of size 8
==55912==    at 0x481F5BC: audit_list_add_dynamic_tag (rtld.c:225)
==55912==    by 0x481F5BC: dl_main (rtld.c:1796)
==55912==    by 0x481C215: _dl_sysdep_start (dl-sysdep.c:140)
==55912==    by 0x481D9EB: _dl_start_final (rtld.c:498)
==55912==    by 0x481D9EB: _dl_start (rtld.c:585)
==55912==    by 0x481C807: ??? (in /usr/lib64/ld-linux-x86-64.so.2)
==55912==    by 0x1: ???
==55912==    by 0x1FFF0000FE: ???
==55912==    by 0x1FFF000104: ???
==55912==  Address 0x8 is not stack'd, malloc'd or (recently) free'd
```
It looks like ld-linux is using a null pointer for the Dynamic region containing Elf64_Dyn structs.  A packed executable has no PT_DYNAMIC, but the expanded contents in memory has the PT_DYNAMIC of the original not-packed executable.  Running upx.packed directly under the shell works, so valgrind is interfering with ld-linux getting the correct value.

This is likely to tale a week to diagnose, then a month to fix or convince valgrind to change.

**Comment by markus-oberhumer** [comment]
Ok thanks, I think we can ignore this for now. But feel free to open an UPX issue if you want to document/tackle this.

**Comment by markus-oberhumer** [comment]
> `MemBufferBase<unsigned char>::operator[]` objects to `&membuf[N]` where `N` is the declared length. The standard explicitly allows taking the address of "just beyond the high-address end", so the test is too strict.

After some more research I've learned that `&v[N]` is actually **invalid** for containers like `std::vector`. Do you think you could change your code to use `membuf + N` instead of `&membuf[N]` ? I could also introduce `begin()` and `end()` member functions if this makes the code cleaner.

**Comment by markus-oberhumer** [comment]
@jreiser It looks like mips-linux and mipsel-linux currently crash when self-packed (running under qemu).

Please see log file https://github.com/upx/upx/actions/runs/7801564334/job/21276997879 and 
https://github.com/upx/upx/actions/runs/7801564334 for zigcc-mips-linux-musl binaries.

**Comment by jreiser** [comment]
@markus-oberhumer   It works for me:
```

$ cd upx-test-misc-cb49cd1-zigcc-mips-linux-musl/zig/mips-linux-musl/release
$ unset UPX_DEBUG_DOCTEST_DISABLE
$ qemu-mips-static ./upx -f -o upx.packed upx
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX git-cb49cd  Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
  18474988 ->   5050352   27.34%   linux/mips    upx.packed                    

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.

$ qemu-mips-static ./upx.packed --version-short
upx 4.3.0-git-cb49cd124a04

$ ls -l
total 29716
-rwxr-xr-x. 1 jreiser jreiser 18474988 Feb  6 06:57 upx
-rwxr-xr-x. 1 jreiser jreiser  5050352 Feb  6 06:57 upx.packed
-rw-r--r--. 1 jreiser jreiser  6898959 Feb 14 14:36 upx.readelf

$ sha256sum upx upx.packed
b2e1afa9b570631554cd4faa80fd713f5d05520e8657923243933116d22567be  upx
13774cab4366c8dcd737d72adda1019f567fedb01a0d4530d90a1171b9d2de49  upx.packed

$ file upx upx.packed
upx:        ELF 32-bit MSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, with debug_info, not stripped
upx.packed: ELF 32-bit MSB executable, MIPS, MIPS32 version 1 (SYSV), statically linked, no section header

```

**Comment by markus-oberhumer** [comment]
@jreiser please test the `debug` build, i.e. `upx-test-misc-cb49cd1-zigcc-mips-linux-musl/zig/mips-linux-musl/debug/upx`

Packed upx crashes for me with `qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped`

**Comment by jreiser** [comment]
@markus-oberhumer  I see the Trace/breakpoint trap in the `debug` build, but not if `export UPX_DEBUG_DOCTEST_DISABLE=1`.  So doctest is suspect.  Here's how to find out where:
```
$ cd upx-test-misc-cb49cd1-zigcc-mips-linux-musl/zig/mips-linux-musl/debug
$ qemu-mips-static ./upx -f -o upx.packed ./upx   ## generate upx.packed for mips
   [[snip: no complaints]]

$ unset UPX_DEBUG_DOCTEST_DISABLE

## run testcase under qemu in background, but wait for gdb on TCP port 1234
$ qemu-mips-static -g 1234 ./upx.packed --version-short & 

$ $GDB_MULTI ./upx.packed   ## gdb which understands mips; see below

(gdb) target remote :1234   ## rendezvous with qemu on TCP port 1234
Remote debugging using :1234
0x009c2860 in ?? ()   ## entry point to upx.packed
(gdb) continue   ## start exeuction by qemu
Continuing.

Program received signal SIGTRAP, Trace/breakpoint trap.
0x0028b1f0 in ?? ()
(gdb) x/9i $pc-4*4   ## instruction stream near point of trap
   0x28b1e0:	and	at,at,v0
   0x28b1e4:	andi	at,at,0x1
   0x28b1e8:	bgtz	at,0x28b1f4
   0x28b1ec:	nop
=> 0x28b1f0:	break
   0x28b1f4:	ldc1	$f0,408(s8)   ## a floating-point instruction: there are none in UPX itself
   0x28b1f8:	trunc.w.d	$f0,$f0
   0x28b1fc:	mfc1	at,$f0
   0x28b200:	sw	at,496(s8)

## load symbol table into gdb
(gdb) shell objdump --section-headers ./upx  |  grep text
  6 .text         005f4ca0  001e80c0  001e80c0  001c80c0  2**4   ## VMA= LMA= 0x001e80c0
(gdb) add-symbol-file ./upx 0x001e80c0   ## get symbols from non-packed upx

(gdb) bt
#0  0x0028b1f0 in doctest::(anonymous namespace)::ConsoleReporter::test_run_end (this=0x3fffbce0, p=...)
    at /__w/upx/upx/vendor/doctest/doctest/parts/doctest.cpp:3205
#1  0x002616dc in doctest::Context::run (this=0x407fede0) at /__w/upx/upx/vendor/doctest/doctest/parts/doctest.cpp:3989
#2  0x001e86cc in upx_doctest_check (argc=0x2, argv=0x407fef74) at /__w/upx/upx/src/check/dt_check.cpp:82
#3  0x003f1fdc in upx_main (argc=0x2, argv=0x407fef74) at /__w/upx/upx/src/main.cpp:1193
#4  0x003f49bc in main (argc=0x2, argv=0x407fef74) at /__w/upx/upx/src/main.cpp:1370

(gdb) dir <<actual_path>>/vendor/doctest/doctest/parts
(gdb) frame 0
#0  0x0028b1f0 in doctest::(anonymous namespace)::ConsoleReporter::test_run_end (this=0x3fffbce0, p=...)
    at /__w/upx/upx/vendor/doctest/doctest/parts/doctest.cpp:3205
3205	            auto totwidth = int(std::ceil(log10(static_cast<double>(std::max(p.numTestCasesPassingFilters, static_cast<unsigned>(p.numAsserts))) + 1)));
(gdb) print p
$1 = (const doctest::TestRunStats &) @0x3fff40e0: {numTestCases = 0x30, numTestCasesPassingFilters = 0x30, numTestSuitesPassingFilters = 0x0, 
  numTestCasesFailed = 0x0, numAsserts = 0x2c3, numAssertsFailed = 0x0}


It's not obvious to me what the compiled code is complaining about.


Debian has a downloadable package with a multi-arch gdb.  To generate one on Fedora:
## You must have an environment variable RPMBUILD which names a directory with space for building,
## and a file $HOME/.rpmmacros with contents at least:
##     $ cat $HOME/.rpmmacros
##     %packager %(echo $USER)
##     %_topdir %(echo <<absolute_path>>/rpmbuild)

$ dnf download --source gdb
$ rpm --install gdb-14.1-3.fc38.src.rpm
$ cd $RPMBUILD/SPECS
$ patch gdb.spec  <__EOF__   ## toss s390 as a target; replace with mips
--- gdb.spec	2023-10-13 17:00:00.000000000 -0700
+++ gdb.spec.jreiser	2023-12-12 13:49:46.784398760 -0800
@@ -649,7 +649,7 @@
 %ifarch sparc sparcv9
 	sparc-%{_vendor}-%{_target_os}%{?_gnu}
 %else
-	--enable-targets=s390-linux-gnu,powerpc-linux-gnu,arm-linux-gnu,aarch64-linux-gnu	\
+	--enable-targets=mips-linux-gnu,powerpc-linux-gnu,arm-linux-gnu,aarch64-linux-gnu \
 	%{_target_platform}
 %endif
 
@@ -749,7 +749,7 @@
 %ifarch sparc sparcv9
 	sparc-%{_vendor}-%{_target_os}%{?_gnu}
 %else
-	--enable-targets=s390-linux-gnu,powerpc-linux-gnu,arm-linux-gnu,aarch64-linux-gnu	\
+	--enable-targets=mips-linux-gnu,powerpc-linux-gnu,arm-linux-gnu,aarch64-linux-gnu \
 	%{_target_platform}
 %endif
 
__EOF__
$ sudo dnf builddep gdb.spec
$ rpmbuild -bc gdb.spec
$ find ../BUILD/gdb-14.1-3 -name gdb
$ export GDB_MULTI=<<absolute_path>>/build-x86_64-redhat-linux-gnu/gdb/gdb
```

**Comment by markus-oberhumer** [comment]
@jreiser I see, thanks for debugging. But now the main question: why does the unpacked binary work, but not the packed one?

Are there some ELF flags/sections that may influence floating point behavior ?

**Comment by jreiser** [comment]
I will continue to investigate the Trap for a while.  But code such as
```
3205	            auto totwidth = int(std::ceil(log10(static_cast<double>(std::max(p.numTestCasesPassingFilters, static_cast<unsigned>(p.numAsserts))) + 1)));
```
is atrocious.  Here is a subroutine which does not use floating point, and is 3 times smaller and 4 times faster than `ceil(log10(unsigned))`:
```
int decimal_width(unsigned x)
{
    int w = 1;
    while (10000 <= x) {
        x /= 10000;
        w  += 4;
    }
    if (100 <= x) {
        x /= 100;
        w += 2;
    }
    if (10 <= x) {
        w += 1;
    }
    return w;
}

#if 1  //{ Exhaustive test
#include <stdio.h>

int main(int argc, char *argv[])
{
    int previous = 0;
    unsigned j = 0;
    do {
        unsigned w = decimal_width(j);
        if (w != previous) {
            printf("j= %d  w=%d\n", j, w);
            previous = w;
        }
    } while (++j);
    return 0;
}
#endif  //}
```

**Comment by jreiser** [comment]
@markus-oberhumer  The compiler for MIPS of 
```
322	        double getElapsedSeconds() const { return static_cast<double>(getCurrentTicks() - m_ticks) / 1000000.0; }
```
guarantees to divide by 0 in floating point, which gives the hardware a license to return a random value, and set the `div0` bit in the floating-point status register, which poisons the results of the extra-careful FP comparisons that the santizer uses, causing the Trap.  [Also, the sanitizer does not clean the FP status register after checking.]

The context is
```
(gdb) bt
#0  0x002c4014 in doctest::detail::Timer::getElapsedSeconds (this=0x3fff5130)
    at /__w/upx/upx/vendor/doctest/doctest/parts/doctest.cpp:322
#1  0x002a0c94 in doctest::detail::ContextState::finalizeTestCaseData (this=0x3fff4060)
    at /__w/upx/upx/vendor/doctest/doctest/parts/doctest.cpp:458
#2  0x00260e84 in doctest::Context::run (this=0x407fee10)
    at /__w/upx/upx/vendor/doctest/doctest/parts/doctest.cpp:3976
#3  0x001e86cc in upx_doctest_check (argc=0x2, argv=0x407fefa4) at /__w/upx/upx/src/check/dt_check.cpp:82
#4  0x003f1fdc in upx_main (argc=0x2, argv=0x407fefa4) at /__w/upx/upx/src/main.cpp:1193
#5  0x003f49bc in main (argc=0x2, argv=0x407fefa4) at /__w/upx/upx/src/main.cpp:1370
```
The generated code is
```
_ZNK7doctest6detail5Timer17getElapsedSecondsEv:
   0x2c3fc0 <+96>:	lw	gp,20(s8)
   0x2c3fc4 <+100>:	lw	t9,-28476(gp)
   0x2c3fc8 <+104>:	jalr	t9   #  0x23d864 <_ZN7doctest6detail15getCurrentTicksEv>
   0x2c3fcc <+108>:	nop
   0x2c3fd0 <+112>:	lw	at,24(s8)
   0x2c3fd4 <+116>:	lw	gp,20(s8)
   0x2c3fd8 <+120>:	lw	a1,0(at)
   0x2c3fdc <+124>:	lw	at,4(at)
   0x2c3fe0 <+128>:	sltu	a0,v1,at
   0x2c3fe4 <+132>:	subu	v0,v0,a1
   0x2c3fe8 <+136>:	subu	a0,v0,a0
   0x2c3fec <+140>:	subu	a1,v1,at
   0x2c3ff0 <+144>:	lw	t9,-26644(gp)
   0x2c3ff4 <+148>:	jalr	t9  # 0x7b75fc <__floatundidf>
   0x2c3ff8 <+152>:	nop
   0x2c3ffc <+156>:	lui	at,0x412e
   0x2c4000 <+160>:	ori	v0,at,0x8480
   0x2c4004 <+164>:	li	at,0   # $at = 0
   0x2c4008 <+168>:	mtc1	at,$f2  # $f2 = 0
   0x2c400c <+172>:	mtc1	v0,$f3
   0x2c4010 <+176>:	div.d	$f0,$f0,$f2  # $f0 = $f0 / $f2
```
So this compiler cannot be trusted to generate correct code for MIPS floating-point arithmetic.  Therefore, turn off DOCTEST when running on MIPS [`export UPX_DEBUG_DOCTEST_DISABLE=1`].

**Comment by markus-oberhumer** [comment]
I've created issue #788 for further discussion of the zig-cc mips problem.

**Comment by markus-oberhumer** [comment]
@jreiser I'd like to release the current devel branch as 4.2.3 some time in the near future; your branch merge will then appear in 4.3.0; milestones have been updated accordingly

**Comment by markus-oberhumer** [comment]
@jreiser I've updated the Task List. Please tell me what you think and feel free to make changes.

**Comment by markus-oberhumer** [comment]
@jreiser We need some official statement on future macOS support. This is your child, so I fear you must decide to either cure or bury it.

**Comment by markus-oberhumer** [comment]
2024-05-02: I've removed 10 stale branches, here are the SHA in case we want to resurrect:

```
  remotes/origin/B-jreiser-merge      3b250ba7 ANDROID_TEST conditional compilation for Linux on ARM
  remotes/origin/devel-merge          99a0d75b clang-format
  remotes/origin/devel4               15f822c6 clang-format
  remotes/origin/jreiser-0327         116d8685 src/pefile.cpp: support relocs of large files
  remotes/origin/jreiser-0919         ebc56f86 clang-format
  remotes/origin/jreiser-0919-merge   75821c18 p_elf_enum.h has columns, so CLANG_FORMAT_EXCLUDE_FILES
  remotes/origin/jreiser-0919-rebased 95f9e257 Use $(cat ...) instead of $(< ...)  [bash-ism ?]
  remotes/origin/jreiser-devel        4de980e4 Merge branch 'jreiser-devel' of https://github.com/upx/upx into jreiser-devel
  remotes/origin/jreiser-issue813     8d4beb98 Syscall on powerpc linux wipes arg registers, unlike x86_64
  remotes/origin/jreiser-lzma         4e07aab3 Licensed LZMA forbids changes; mandates poor error reporting and recovery
```
